-- CREATE TABLE AYAYA (
--     title VARCHAR,
--     titleRom VARCHAR, 
--     annid INT,
--     song VARCHAR,
--     artist VARCHAR,
--     opedin VARCHAR,
--     video VARCHAR,
--     audio VARCHAR
--     -- );

-- INSERT INTO AYAYA (
--     title,
--     titleRom, 
--     annid,
--     song,
--     artist,
--     opedin,
--     video,
--     audio) VALUES (
--     "My Hero Academia",
--     "Boku no Hero Academia",
--     18485,
--     "Sora ni Utaeba",
--     "amazarashi",
--     "Opening 2",
--     "https://files.catbox.moe/k0myox.webm",
--     "https://files.catbox.moe/u09jit.mp3"
--     ); 